p8105_hw3_zy2378
================
zy
10/18/2021

``` r
library(p8105.datasets)
library(tidyverse)
```

    ## ─ Attaching packages ──────────────────── tidyverse 1.3.1 ─

    ## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.1     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ─ Conflicts ───────────────────── tidyverse_conflicts() ─
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(ggplot2)
data("instacart")
data("brfss_smart2010")
instacart
```

    ## # A tibble: 1,384,617 x 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1        1      49302                 1         1  112108 train               4
    ##  2        1      11109                 2         1  112108 train               4
    ##  3        1      10246                 3         0  112108 train               4
    ##  4        1      49683                 4         0  112108 train               4
    ##  5        1      43633                 5         1  112108 train               4
    ##  6        1      13176                 6         0  112108 train               4
    ##  7        1      47209                 7         0  112108 train               4
    ##  8        1      22035                 8         1  112108 train               4
    ##  9       36      39612                 1         0   79431 train              23
    ## 10       36      19660                 2         1   79431 train              23
    ## # … with 1,384,607 more rows, and 8 more variables: order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>, product_name <chr>,
    ## #   aisle_id <int>, department_id <int>, aisle <chr>, department <chr>

``` r
?ggplot
```

## Data Description

The Instacart data contains observations on 1384617 orders from
instacart store online. The data include 15 variables, and are the
characteristics of the orders and the product，including product name,
product id, order name, etc. For observation at row1, the order is id is
1, and product id is 49302, the order that the product was add to chart
is 1, and it have been ordered before by this customer. The user id is
112108, and the order belongs to the train evaluation set. The order
number for this user is 4, and the order was placed on Thursday 10am. It
have been 9 days since this user’s last order, and the product is
Bulgarian Yogurt. The aisle id is 120, and the product belongs to the
yogurt aisle. The department id is 16, and is dairy eggs.

``` r
aisle_df1=
  instacart%>%
  group_by(aisle)%>%
  summarize(n_obs=n())%>%
  mutate(rank=rank(n_obs))

aisle_df2=
  aisle_df1%>%
  filter(n_obs>=10000)%>%
  select(-rank)
aisle_df2
```

    ## # A tibble: 39 x 2
    ##    aisle                    n_obs
    ##    <chr>                    <int>
    ##  1 baby food formula        13198
    ##  2 baking ingredients       13088
    ##  3 bread                    23635
    ##  4 butter                   10575
    ##  5 candy chocolate          11453
    ##  6 canned jarred vegetables 12679
    ##  7 canned meals beans       11774
    ##  8 cereal                   16201
    ##  9 chips pretzels           31269
    ## 10 crackers                 19592
    ## # … with 29 more rows

# 

1.  There are 134 aisles, and the most items that ordered from is the
    fresh vagetables aisle.

``` r
baking_ingredients_df=
  instacart%>%
  filter(aisle=="baking ingredients")%>%
  group_by(product_name)%>%
  summarize(n_obs=n())%>%
  mutate(rank=rank(n_obs))%>%
  filter(rank>=521)%>%
  select(-rank)%>%
  mutate(aisle=c("baking ingredients","baking ingredients","baking ingredients"))%>%
  select(aisle,product_name,n_obs)
baking_ingredients_df
```

    ## # A tibble: 3 x 3
    ##   aisle              product_name      n_obs
    ##   <chr>              <chr>             <int>
    ## 1 baking ingredients Cane Sugar          336
    ## 2 baking ingredients Light Brown Sugar   499
    ## 3 baking ingredients Pure Baking Soda    387

``` r
dog_food_care_df=
  instacart%>%
  filter(aisle=="dog food care")%>%
  group_by(product_name)%>%
  summarize(n_obs=n())%>%
  mutate(rank=rank(n_obs))%>%
  filter(rank>=353)%>%
  select(-rank)%>%
  mutate(aisle=c("dog food care","dog food care","dog food care"))%>%
  select(aisle,product_name,n_obs)
dog_food_care_df
```

    ## # A tibble: 3 x 3
    ##   aisle         product_name                                  n_obs
    ##   <chr>         <chr>                                         <int>
    ## 1 dog food care Organix Chicken & Brown Rice Recipe              28
    ## 2 dog food care Small Dog Biscuits                               26
    ## 3 dog food care Snack Sticks Chicken & Rice Recipe Dog Treats    30

``` r
packaged_vegetables_fruits_df=
  instacart%>%
  filter(aisle=="packaged vegetables fruits")%>%
  group_by(product_name)%>%
  summarize(n_obs=n())%>%
  mutate(rank=rank(n_obs))%>%
  filter(rank>=564)%>%
  select(-rank)%>%
  mutate(aisle=c("packaged vegetables fruits","packaged vegetables fruits","packaged vegetables fruits"))%>%
  select(aisle,product_name,n_obs)
packaged_vegetables_fruits_df
```

    ## # A tibble: 3 x 3
    ##   aisle                      product_name         n_obs
    ##   <chr>                      <chr>                <int>
    ## 1 packaged vegetables fruits Organic Baby Spinach  9784
    ## 2 packaged vegetables fruits Organic Blueberries   4966
    ## 3 packaged vegetables fruits Organic Raspberries   5546

``` r
bind_rows(baking_ingredients_df,dog_food_care_df,packaged_vegetables_fruits_df)
```

    ## # A tibble: 9 x 3
    ##   aisle                      product_name                                  n_obs
    ##   <chr>                      <chr>                                         <int>
    ## 1 baking ingredients         Cane Sugar                                      336
    ## 2 baking ingredients         Light Brown Sugar                               499
    ## 3 baking ingredients         Pure Baking Soda                                387
    ## 4 dog food care              Organix Chicken & Brown Rice Recipe              28
    ## 5 dog food care              Small Dog Biscuits                               26
    ## 6 dog food care              Snack Sticks Chicken & Rice Recipe Dog Treats    30
    ## 7 packaged vegetables fruits Organic Baby Spinach                           9784
    ## 8 packaged vegetables fruits Organic Blueberries                            4966
    ## 9 packaged vegetables fruits Organic Raspberries                            5546

``` r
pink_lady_apples_df=
  instacart%>%
  filter(product_name=="Pink Lady Apples")%>%
  select(product_name,order_dow,order_hour_of_day)%>%
  group_by(order_dow)%>%
  summarize(mean=mean(order_hour_of_day))%>%
  mutate(product_name=rep("Pink Lady Apples",7))%>%
  select(product_name,order_dow,mean)
pink_lady_apples_df
```

    ## # A tibble: 7 x 3
    ##   product_name     order_dow  mean
    ##   <chr>                <int> <dbl>
    ## 1 Pink Lady Apples         0  13.4
    ## 2 Pink Lady Apples         1  11.4
    ## 3 Pink Lady Apples         2  11.7
    ## 4 Pink Lady Apples         3  14.2
    ## 5 Pink Lady Apples         4  11.6
    ## 6 Pink Lady Apples         5  12.8
    ## 7 Pink Lady Apples         6  11.9

``` r
coffee_ice_cream_df=
  instacart%>%
  filter(product_name=="Coffee Ice Cream")%>%
  select(product_name,order_dow,order_hour_of_day)%>%
  group_by(order_dow)%>%
  summarize(mean=mean(order_hour_of_day))%>%  
  mutate(product_name=rep("Coffee Ice Cream",7))%>%
  select(product_name,order_dow,mean)
coffee_ice_cream_df
```

    ## # A tibble: 7 x 3
    ##   product_name     order_dow  mean
    ##   <chr>                <int> <dbl>
    ## 1 Coffee Ice Cream         0  13.8
    ## 2 Coffee Ice Cream         1  14.3
    ## 3 Coffee Ice Cream         2  15.4
    ## 4 Coffee Ice Cream         3  15.3
    ## 5 Coffee Ice Cream         4  15.2
    ## 6 Coffee Ice Cream         5  12.3
    ## 7 Coffee Ice Cream         6  13.8

``` r
df_mean_order_hour_of_day=
  bind_rows(pink_lady_apples_df,coffee_ice_cream_df)%>%
  pivot_wider(names_from = order_dow,values_from=mean)%>%
  rename("Sunday"="0","Monday"="1","Tuesday"="2","Wednesday"="3","Thursday"="4","Friday"="5","Saturday"="6")
df_mean_order_hour_of_day
```

    ## # A tibble: 2 x 8
    ##   product_name     Sunday Monday Tuesday Wednesday Thursday Friday Saturday
    ##   <chr>             <dbl>  <dbl>   <dbl>     <dbl>    <dbl>  <dbl>    <dbl>
    ## 1 Pink Lady Apples   13.4   11.4    11.7      14.2     11.6   12.8     11.9
    ## 2 Coffee Ice Cream   13.8   14.3    15.4      15.3     15.2   12.3     13.8
